### ISSUE TITLE
Inconsistent Datepicker Weekday Labels

### ISSUE THREAD

**Issue by Ncookiez** [themesberg/flowbite-react#1044]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to https://www.flowbite-react.com/docs/components/datepicker
2. Click on the first datepicker example to view selector

## Current behavior

The datepicker component is currently showing different weekdays for different users.

User A:
![image](https://github.com/themesberg/flowbite-react/assets/22108522/44c7f236-9a22-42e8-9191-57f547412613)

User B:
![image](https://github.com/themesberg/flowbite-react/assets/22108522/37f88c70-7048-4ef7-81de-ca67bfb75748)

## Expected behavior

Ideally these are always correct regardless of timezone, locale, or browser.

In this case, weekday labels should be starting on Sunday, and ending on Saturday to match correctly with the numbers below.

## Context

In my case I fall into the "User A" category, seeing the wrong weekday labels. Can replicate this on Edge and Brave Browser (both Chromium-based). I am currently on GMT-4 timezone-wise. English locale.

This could be caused by a variety of issues as hinted above - the default `weekStart` [on the component](https://github.com/themesberg/flowbite-react/blob/main/src/components/Datepicker/Datepicker.tsx#L102) is set to Sunday, and I don't see this being overwritten on the docs app, so maybe something is wrong with how context is being gathered [here](https://github.com/themesberg/flowbite-react/blob/main/src/components/Datepicker/DatepickerContext.tsx#L23), either due to locale or timezone specifics.

Alternatively, this could be due to timezone or locale issues on the `getWeekDays()` function [here](https://github.com/themesberg/flowbite-react/blob/main/src/components/Datepicker/helpers.ts#L66), although somewhat unlikely.

**Comment by Cesron** [comment]
In my case, the output I receive is as follows:

![image](https://github.com/themesberg/flowbite-react/assets/68670422/b651ca25-6c9a-41d6-8e5e-a673e54beda2)

I'm using the Edge browser with UTC-6 time zone and Spanish locale.

I've also noticed that in the original [Flowbite library](https://flowbite.com/docs/plugins/datepicker/), it works perfectly with the same browser and time zone configuration:

![image](https://github.com/themesberg/flowbite-react/assets/68670422/607e20d4-22b2-4031-ae69-f14a4e5bbe64)

There's another problem, but I'm not sure if it's related. The issue is that when I open the decades menu, I'm not able to click on any decade other than 2:

![image](https://github.com/themesberg/flowbite-react/assets/68670422/3885221e-7a81-4e15-aa48-576ecbe995fd)

**Comment by matheusalxds** [comment]
I have exactly the same problem.

**Comment by matheusalxds** [comment]
Is there any udpdate?

**Comment by AdilsonDevTech** [comment]
No updates yet 😢
