### ISSUE TITLE
Popover component not exported but listed in docs

### ISSUE THREAD

**Issue by rahuladaptavist** [themesberg/flowbite-react#1274]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Install flowbite-react package
2. Try to use https://www.flowbite-react.com/docs/components/popover
3. It can't find any exported component as Popover

## Current behavior
Gives error on import

## Expected behavior
Should be able to use Popover as mentioned in the docs

**Comment by dhavalveera** [comment]
@rahuladaptavist -- `Popover` component feature has been added, but it has not been released yet on the NPM. The reason it's available on the Flowbite React website is when a `feature` or `bug fixes` is getting merged to the main branch or production branch, it auto-deploying the docs to the `https://flowbite-react.com` due to which you can able to find the `Popover` component feature on the Docs.

**Comment by SutuSebastian** [comment]
Known issue, this will get fixed in the next version of this repo architectur (see #1264 ).

**Comment by ttnnphuoc** [comment]
May i know How long we can get this in new version?

**Comment by jonyboom** [comment]
Also interested in getting access to the popover so commenting here to track.

**Comment by SutuSebastian** [comment]
Prepping a release as we speak.

**Comment by SutuSebastian** [comment]
> Prepping a release as we speak.

Released, check [v0.7.3](https://github.com/themesberg/flowbite-react/releases/tag/v0.7.3).

**Comment by jonyboom** [comment]
Thanks for the quick turn around. Will be pulling the release in shortly.
