### ISSUE TITLE
Carousel : cant modify height

### ISSUE THREAD

**Issue by loicy** [themesberg/flowbite-react#168]
**Describe the bug**
It is not possible to change the height of the carousels. Changing the width works correctly.

**To Reproduce**
Put a carousel in any div and change the size with a class in that div to h-32 (for example).

**Expected behavior**
The carousel should take the size allocated in the class of the div.

**Screenshots**

![Sans titre-3](https://user-images.githubusercontent.com/36493474/171005959-6ff03caa-7f9d-44f0-98ad-b756f1da51ff.png)

in code :
`
className="relative w-full h-full"
`

**Comment by rluders** [comment]
The issue seems to be caused by the element that has `h-56` class added to it.

**Comment by tulup-conner** [comment]
I will add theming for Carousels next so we can fix this for ya.

**Comment by rluders** [comment]
@tulup-conner theme support will not fix the bug completely. Since, you can have multiple carousels, each with different sizes. We need to allow the carousel to "fit" to the parent div size, so it will allow the users to use it in multiple sizes.

**Comment by tulup-conner** [comment]
Ok, this isn't how it is written in the regular Flowbite component, but I decided to change `h-56 sm:h-64 xl:h-80 2xl:h-96` to `min-height`s, then moved those rules to `theme.carousel.base`.

Now, users can wrap their `Carousel` in a `div` with a specific height and it will respect that height. Otherwise, it will use the default heights specified by Flowbite.

See #208
