### ISSUE TITLE
Navbar and Header changes color by their own

### ISSUE THREAD

**Issue by 1eurs** [themesberg/flowbite-react#245]
**Describe the bug**
the navbar won't let me change its color to my background color but every other color is possible ?_? but after a white it go back to white.

**Desktop (please complete the following information):**

- Windows 
- brave
- newest

**Comment by rluders** [comment]
@1eurs are u using the latest version of the library? If yes, you need to change your sidebar color by using the theme system.

**Comment by tulup-conner** [comment]
@1eurs have you had the chance to create a reproduction of this issue?

**Comment by tulup-conner** [comment]
@1eurs I'm going to close this since we haven't heard back, but please feel free to reopen if you can't use a theme on the Navbar to do what you want. You can find an example of adding a theme here: 

https://github.com/tulupinc/flowbite-next-starter/blob/main/src/theme.ts
https://github.com/tulupinc/flowbite-next-starter/blob/main/src/pages/_app.tsx
