### ISSUE TITLE
Rating doesn't work as it should.

### ISSUE THREAD

**Issue by elhe26** [themesberg/flowbite-react#257]
**Describe the bug**
Rating doesn't change the size of the Star Icon. `Rating.Star` doesn't get filled.

**To Reproduce**
```typescript
  <Rating size="md">
    <Rating.Star />
    <Rating.Star />
    <Rating.Star />
    <Rating.Star />
    <Rating.Star filled={false} />
  </Rating>
```

 Doesn't work.

**Expected behavior**
Star gets a yellow color and Star with `filled={false}` gets a gray color.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: v1.40.109

**Comment by rluders** [comment]
I'm using the exactly same browser and I don't see the issue.
Can you check if you are using the version `0.1.0` of flowbite-react?

**Comment by elhe26** [comment]
- I'm using version `0.1.0`
- Example work is ok. I can see all stars.

**Comment by rluders** [comment]
Hello, @elhe26 

I wasn't able to reproduce the issue that you are having. Everything seems to be working fine. I created an CRA project, installed the lasted Flowbite React, and used the exactly same code that you did, and the result was as expected, no issue showed up.

In order to proceed, could you please provide some:
- screenshot of the issue
- complete code
- are u using cra, nextjs or something else?

**Comment by elhe26** [comment]
Hi @rluders ,

After I upgraded Nextjs to the latest version, everything started working.

Thanks.
