### ISSUE TITLE
Breadcrumb shows leading arrow when there's no icon

### ISSUE THREAD

**Issue by tzusman** [themesberg/flowbite-react#264]
The issue: I'd expect there not to be an arrow to the left of the first element

![image](https://user-images.githubusercontent.com/113902/177342347-69ca68b8-28d6-46fe-975c-cb958e448abc.png)
---

```
<Breadcrumb>
    <Breadcrumb.Item>
        AAA
    </Breadcrumb.Item>
    <Breadcrumb.Item>
        BBB
    </Breadcrumb.Item>
    <Breadcrumb.Item>
        CCC
    </Breadcrumb.Item>
    <Breadcrumb.Item>
        DDD
    </Breadcrumb.Item>
    <Breadcrumb.Item>
        EEE
    </Breadcrumb.Item>
</Breadcrumb>
```

**Comment by rluders** [comment]
@tzusman what version of flowbite are you using?

**Comment by tzusman** [comment]
```
flowbite: 1.4.7
flowbite-react: 0.1.2
```

**Comment by tzusman** [comment]
@rluders I don't see a v0.1.3 in npm or in the github repo - could you please point me to it?

**Comment by rluders** [comment]
Ops! My bad, @tzusman, I was thinking to release the `0.1.3` today, but I'm waiting for a PR.

Anyway, I tested with `0.1.2` and it also didn't had any issue. So... 

- Could you please provide some extra context?
- If you project is open source, could you share the repo with the code? 
- Otherwise, could you provide some more detailed example?

**Comment by tzusman** [comment]
@rluders I created a new Vite app, but it worked properly when it wasn't within the context of my app.  I'll try to dig into it and see if I can find the culprit.
