### ISSUE TITLE
Next.js SSR Hydration error with Modal component

### ISSUE THREAD

**Issue by AhmedA1559** [themesberg/flowbite-react#269]
**Describe the bug**
With Next.js alongside flowbite-react, using Modals in the DOM causes errors with Next.js's builtin SSR.

**To Reproduce**

1. Initialize Next.js project (create-next-app)
2. Setup tailwind, Flowbite, and flowbite-react library
3. Import and use Modal component
4. Open development page and see error

Simple repository to replicate the error:
https://github.com/AhmedA1559/modal-example

**Expected behavior**
Using modals should render properly with Next.js's SSR, producing no errors.

**Screenshots**
![First error page](https://media.discordapp.net/attachments/922401356617244733/994512042897711134/Screen_Shot_2022-07-07_at_10.53.35_AM.png)
![Second error page](https://media.discordapp.net/attachments/922401356617244733/994512043166158928/Screen_Shot_2022-07-07_at_10.53.48_AM.png)
![Third error page](https://media.discordapp.net/attachments/922401356617244733/994512043401035836/Screen_Shot_2022-07-07_at_10.53.51_AM.png)

**System information:**

- Device: macOS M1 Pro (2021)
- Resolution: 3024×1964
- OS: macOS
- Browser: Safari
- Version: Version 15.4 (17613.1.17.1.13)

**Project information:**
`npm list --depth=0
├── autoprefixer@10.4.7
├── eslint-config-next@12.2.0
├── eslint@8.19.0
├── flowbite-react@0.1.3
├── flowbite@1.4.7
├── next@12.2.0
├── postcss@8.4.14
├── react-dom@18.2.0
├── react-icons@4.4.0
├── react@18.2.0
└── tailwindcss@3.1.4`

**Comment by julianYaman** [comment]
I also got similar errors and got it fixed in multiple ways:

One would be by wrapping the Modal component in a [Suspense](https://reactjs.org/docs/react-api.html#reactsuspense) component, which was introduced in React 18 without being experimental anymore.

Another solution is by using `useEffect` and states.
`useEffect` (in my example) will be triggered when the HTML was fully rendered.

You could do something like this to have your Modal shown after the site was rendered.

```js
// ...
const [isLoading, setIsLoading] = useState(false)

useEffect(() => {
        setIsLoading(true)
}, [])

// ....

return (
   // ...
   {
     isLoading ? <Modal></Modal> : null
   }
)

``` 

An example how I use this fix currently would be [this (and the following) line(s) in my component](https://github.com/julianYaman/tooldb/blob/0fad181537e534d622d437f26af82d7b6d18be4c/components/Main.tsx#L50).

Possible explanations why this might happen in Next.js as well as further fixes can be found
- [in this answer here by juliomalves on StackOverflow](https://stackoverflow.com/a/66374800)
- and in this endless discussion at the repo of Next.js: https://github.com/vercel/next.js/discussions/35773

**Comment by tulup-conner** [comment]
I've tried to play around with this but I'm honestly stumped. My understanding is that this happening because the `Modal` is created in a `React.Portal`. There's no HTML delivered to the spot where the `Modal` is actually declared. But I don't know how to help `next` understand/deal with that.

**Comment by rluders** [comment]
Fixed.

**Comment by Karabur** [comment]
I have the same issue on the latest flowbite-react. 0.10.2
As there is no info on what commit/version/PR fix has been done or on the fix itself, it is hard to provide more details.
