### ISSUE TITLE
How to edit components?

### ISSUE THREAD

**Issue by crypt096** [themesberg/flowbite-react#366]
E.g. I want to change navbar / footer / link colors. I am not aware on how I could do such a thing?

**Comment by lukemurray7** [comment]
Yeh - we should be able to override the classnames of components - i'm stuck because the Carousel has a fixed height..

**Comment by rluders** [comment]
Right now you can customize it only using the theme support. We are planning to give access to the `className` property again, but still, need to decide how it is going to work along with the theme support.

I'm closing this one, since it is already a "in progress" discussion that will lead for a implementation task in the future.

**Comment by EstebanVictorio** [comment]
@rluders I have one last question about this.

The docs say that the theme is an experimental feature that might potentially change.

Is that notice up to date or is theming still a WIP?
