### ISSUE TITLE
Addition of Footer

### ISSUE THREAD

**Issue by tanya172** [themesberg/flowbite-react#379]
The addition of Footer to the website will enhance it.

Kindly assign me this issue and add the Hacktoberfest label. @themesberg

**Comment by rluders** [comment]
Sorry. I don't get it. You are saying that the flowbite-react.com layout has no Footer? Or there is a missing Footer layout in the component documentation?

**Comment by tanya172** [comment]
There is no footer section on the webpage. Since every website has a footer so I feel there is a need for footer where we can mention further information, for instance, about us, the company's name, social media links

**Comment by rluders** [comment]
All right, got it @tanya172. I'm not sure if we need but... lets discuss it. :)

@tulup-conner  @zoltanszogyenyi what do you think? Do we need a footer at the current flowbite-react.com? If so, what information would be nice to have?

TBH, I don't see any benefit right now, since we are planning for a long time to move the documentation to Hugo. But, please, let me know what you folks think about it.

**Comment by rluders** [comment]
Well, it seems that since nobody replied to it, I'll keep my opinion that there is no benefit right now, since we will move the documentation to Hugo.

Thanks for the suggestion anyway. If you are interested to contribute with the project there are some [open issues that needs help](https://github.com/themesberg/flowbite-react/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).
