### ISSUE TITLE
Header navigation menu not expanding on mobile view

### ISSUE THREAD

**Issue by johngouf** [themesberg/flowbite-react#386]
**Describe the bug**
Followed the instructions to setup a flowbite-react project.
Copied the code for header block in https://flowbite.com/blocks/marketing/header/
Everything works fine except when I switch to mobile view that the navigation menu doesn't expand on click

**Expected behavior**
The side menu to expand

**System information:**

- Device:
- Resolution:
- OS: Ubuntu
- Browser: Firefox/Chrome
- Version:

**Project information:**

- Tailwind: 3.1.8
- Flowbite: 1.5.3
- Flowbite React: 0.1.2
- Type: CRA

**Comment by johngouf** [comment]
Just an update on this. When I added:
```
<script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
```
in the <body> element in index.html it worked.

Do we also need to do that?

**Comment by rluders** [comment]
Well, nope. Do not mix standard flowbite javascript with flowbite-react, please.

**Comment by yiannis-zen** [comment]
Ah got it, sorry I didn't realise that the code blocks we should be using are these: https://flowbite-react.com/
Just a suggestion so that other people don't get confused:
Maybe here: https://flowbite.com/docs/getting-started/react/ we could add a warning that blocks from here https://flowbite.com/blocks/ won't work
