### ISSUE TITLE
Classnames not adding to <Toast.Toggle className="here" />

### ISSUE THREAD

**Issue by pupupue** [themesberg/flowbite-react#444]
Tried to override

`<Toast.Toggle className="absolute top-2 right-2" />`

but any classname i add doesn't seem to work.

Checked the source code, and this obvious prop is missing in the code, so im perplexed.

Since you've declared the prop to extend buton props, please spread them to the component or update the union

ToastToggle.d.ts
```
declare type ToastToggleProps = ComponentProps<'button'> & {
    xIcon?: FC<ComponentProps<'svg'>>;
};
```

ToastToggle.js
`export const ToastToggle = ({ xIcon: XIcon = HiX }) => `

to

`export const ToastToggle = ({ xIcon: XIcon = HiX, ...rest }) => `

**Comment by wahabshah21** [comment]
This could be the case with Tabs Component too. Adding classes doesn't seem to work.

**Comment by rluders** [comment]
I can confirm this one, it should be pretty easy to fix. Since the component props already extend `button`, what needs to be done is:

https://github.com/themesberg/flowbite-react/blob/2a452c9131acc77f23011c67356f3ef3828ef0a0/src/lib/components/Toast/ToastToggle.tsx#L10

Add the `...props` to the function.

https://github.com/themesberg/flowbite-react/blob/2a452c9131acc77f23011c67356f3ef3828ef0a0/src/lib/components/Toast/ToastToggle.tsx#L20

And them, use the `{...props}` at the `button` tag.

**Comment by rluders** [comment]
Not sure about the `Tab` issue. I think that component needs some refactoring. It is doing too much magic IMHO.
