### ISSUE TITLE
flowbite-react slows down my page

### ISSUE THREAD

**Issue by RotrixLOL** [themesberg/flowbite-react#469]
**Describe the bug**
My site practically does not load. I have investigated the cause with chrome devtools and found it to be flowbite.

**To Reproduce**

1. Clone `RotrixLOL/meme-studio`
2. Install dependencies (npm/pnpm/yarn)
3. Run `npm run dev`
4. Open site and see the behaviour

**Expected behavior**
The page loads much faster.

**Screenshots**
![image](https://user-images.githubusercontent.com/68074047/205512875-22dc3f91-5a58-4cce-81e1-edc4394ae795.png)

**System information:**

- Device: All (Desktop)
- Resolution: 2560x1440
- OS: All (OS X)
- Browser: Chrome
- Version: Latest

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.5.4
- Flowbite React: 0.3.6
- Type: Vitejs

**Comment by rluders** [comment]
I'm very curious about this one, 'cause I'm using flowbite-react 0.3.6 extensively in my application and I didn't notice anything related to slowing down caused by the library. I'm not saying that it can't be possible, just saying that I didn't experience anything similar.

It is worth investigating. Has anyone else had a similar issue?

Probably is working to debug your application, add some breakpoints to it, and dissect it by partially removing the components to identify the piece that could be causing the issue.

I'm not sure if I'll have time to do it right now, but... if you want to dissect it, @RotrixLOL, and bring more information to the table, it would be nice.

So, to clarify my recommendation:

- Start your application
- It will not work properly
- Remove one component, for example, `Navbar`, and see if it renderers.
- If still not rendering, remove another component, and try it again.
- Repeat, until you identify the piece that could be causing the issue.
- Put back all the other pieces, except the one that is "broken" and see if the issue gets solved.
- Tell us what you figure out.

It is possible that your issue is being caused by some specific component, so, it would be nice to at least isolate the problem.

BTW, anyone that would like to help with this one could reproduce the steps that I mention above since the project code is available on GitHub.

**Comment by RotrixLOL** [comment]
I think no one haves this issue.
In general, I didn't find any component that is breaking the app.

So experimenting: move from pnpm to npm and trying to **remove tailwind**; I found that is **tailwind**.
When I make a request without using anything related to flowbite and having all components disabled, index.css, in which I'm importing tailwind, **is trying to compile**.

So I don't have tailwind's styles compiled, so maybe that's why.

Btw, Can you guys help me optimize tailwind and flowbite?

**Comment by RotrixLOL** [comment]
Oh, this is so confusing 😅😅. Now I see that is the `Footer` component. And I don't know what is happening.
PD: Now I have compiled tailwind.

**Comment by RotrixLOL** [comment]
I'm so stupid 🫠.
```jsx
import { Footer as FwFooter } from "flowbite-react";

const Footer = () => {
  return (
    <Footer container={true}>
```
Anyway, thank you!
