### ISSUE TITLE
Unit test for Carousel

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#49]
**Is your feature request related to a problem? Please describe.**
The component is missing its unit test.

**Describe the solution you'd like**
Implement the unit test to the component.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
Ill take this

**Comment by tulup-conner** [comment]
I'm going to need help with this issue. For some reason, when I render a `Carousel` in jest, it sets the `activeItem` to `NaN`, and I can't interact with the carousel to run any meaningful tests. It would be nice if someone else could try and pick this up, since I imagine I'm missing something obvious

**Comment by rluders** [comment]
@tulup-conner do we have a WIP PR for this one?

**Comment by tulup-conner** [comment]
@rluders I never made one, no. My branch for this was just a spec file with one test, which the gist for that should still be in Discord
