### ISSUE TITLE
Dropdown issue while resize browser window

### ISSUE THREAD

**Issue by goodok21** [themesberg/flowbite-react#662]
When user trying to resize browser window to make it smaller then Floating component (used by Dropdown for example) do smth like this:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/10902227/224491716-3aceeca9-c4bd-420b-95f2-51c9d0e9fd86.png">

the issue in the code:

https://github.com/themesberg/flowbite-react/blob/be78e5e748a64ee213018837c576a75ed35a4f13/src/lib/components/Floating/Floating.tsx#L129

what about using another mechanism to hide dropdown content like display, visibility, opacity and translate to avoid this issue?

**Comment by goodok21** [comment]
or at least add `relative` to wrapper, I think it can do a thing

**Comment by tulup-conner** [comment]
Yeah, I'm not seeing this either myself anymore. The Dropdown theme has changed since this issue was created, so it's possible we "fixed" it, particularly since we have also upgraded several versions of the underlying component, Floating UI, since then. I'll close but feel free to create a new issue if you are still encountering this. I tried all the dropdowns on the docs in Firefox and Chrome with no issues on window resize.
