### ISSUE TITLE
 Placement Attribute of the Modal Component doesn't work

### ISSUE THREAD

**Issue by Wookji-Yoon** [themesberg/flowbite-react#760]
I encountered an issue where the placement attribute of the Modal component is not functioning as expected. Here are the details:

I implemented the Modal component as follows:

```
<Modal
  show={false}
  position="top-right"
  onClose={onClose}
>
  {/* ...data... */}
</Modal>

```
However, regardless of the specified position attribute, the Modal continues to appear in the default position. I have also checked the official documentation page for the Modal component at [flowbite-react.com/modal](https://flowbite-react.com/modal), but the mentioned feature does not work there either.

This issue needs attention and should be addressed to ensure the correct functioning of the placement attribute in the Modal component.

**Comment by tulup-conner** [comment]
Yeah, this is consistent with the documentation: https://flowbite-react-phi.vercel.app/docs/components/modal

We have an open PR that will fix this #766 and I'm waiting for cooperation with the user who submitted that since we just totally rewrote most of the code in this repository. You'll see here once that's been merged.
