### ISSUE TITLE
Warning: Prop `id` did not match. Server: ":RcmpcqH1:" Client: ":R1ir5j9H1:"

### ISSUE THREAD

**Issue by studiolama** [themesberg/flowbite-react#921]
Issue description
When i am using dropdown inside Navbar as a separate component it is throwing this warning
`app-index.js:31  Warning: Prop `id` did not match. Server: ":RcmpcqH1:" Client: ":R1ir5j9H1:"
`

Expected behavior
There should not be any warning

System information:

Device: Macbook m2 
Resolution: 1920*1080
OS: M2 mac
Browser: Chrome
Version: 13.5 (22G74)

Tailwind: 3.3.2
Flowbite: 1.6.5
Flowbite React: 0.5.0
Type: npx create-next-app@latest

**Comment by rluders** [comment]
@studiolama are you using the `use client;` directive?

**Comment by studiolama** [comment]
yes i am using

**Comment by studiolama** [comment]
This is how it is showing in browser

`app-index.js:31 Warning: Prop `id` did not match. Server: ":R3j6pcqH1:" Client: ":Recr5j9H1:"
    at button
    at Trigger (webpack-internal:///(app-pages-browser)/./node_modules/flowbite-react/lib/esm/components/Dropdown/Dropdown.js:35:20)
    at DropdownComponent (webpack-internal:///(app-pages-browser)/./node_modules/flowbite-react/lib/esm/components/Dropdown/Dropdown.js:50:30)
    at UserDropMenu (webpack-internal:///(app-pages-browser)/./src/components/utils/UserDropMenu.js:26:80)
    at div
    at div
    at nav
    at NavbarComponent (webpack-internal:///(app-pages-browser)/./node_modules/flowbite-react/lib/esm/components/Navbar/Navbar.js:26:28)
    at AppNavbar (webpack-internal:///(app-pages-browser)/./src/components/layouts/AppNavbar.js:26:80)
    at div`

**Comment by tulup-conner** [comment]
Hi there, just so you know, this is just a warning and it won't impact your app in a meaningful way. If you run this app in production, with `next start`, you shouldn't see this anymore.

@rluders asked about the `"use client";` directive because this warning indicates your Next.js app renders twice - once on the server, then again when you as the client load your development server in the browser - and an `id` is generated randomly each time. Adding  `"use client";` should prevent this from showing up on the `<Dropdown>` trigger element, but it's not perfect.

It's possible you can remove this by adding a `"use client";` somewhere else in the tree - either your `UserDropMenu` or `AppNavbar` may be missing it. I can't guarantee that, but it's worth trying. We're working on a solution to this for Next.js users, so stay tuned.

Let me know if that suggestion works, or if you are able to find something else that prevents this from happening.

**Comment by studiolama** [comment]
Hi @tulup-conner  thanks for reply but we have tried adding "use client" everywhere in all the possible components that we are using but still getting this warning. That's why we raised this issue.

**Comment by remibeaufils** [comment]
i'm facing the exact same problem
also tried adding "use client" but still getting the warning
could you solve it @studiolama  ?

**Comment by studiolama** [comment]
> i'm facing the exact same problem also tried adding `use client` but still getting the warning
> 
> could you solve it @studiolama ?
> 
> do you have an estimated date for the solution to this for Next.js @tulup-conner ?

Not yet still facing same issue

**Comment by tulup-conner** [comment]
This is an issue with Floating UI, and it will remain an issue until they improve compatibility with RSC in this regard, or we create our own tools for dropdowns, etc. (why we are currently using theirs)
